FROM jenkins/jenkins

USER root

#install terraform

RUN apt-get update && \
apt-get install wget unzip python-pip -y \
wget https://releases.hashicorp.com/terraform/0.13.3/terraform_0.13.3_linux_amd64.zip \
unzip terraform.zip -d ${JENKINS_HOME}/project/terraform
RUN rm -rf terraform.zip

USER jenkins
