FROM jenkins/jenkins

USER root

TERRAFORM_VERSION="0.13.3"

#install terraform

RUN sudo yum install wget zip python-pip -y && \
curl -o terraform.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
unzip terraform.zip -d /var/jenkins_home/project/terraform && \
rm -rf terraform.zip && \

USER jenkins
